### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by EvgeniyMakhmudov** [ivangermes/tc_origins_stats_microservice#1]
https://github.com/ivangermes/testovoe_mongo/blob/main/source/service.py#L9
PEP8 - комментарий в конце должен быть отделен двумя символами пробела перед символом `#` и одним после:
```python
# from datetime import datetime  # python3.11 isoparse
```

https://github.com/ivangermes/testovoe_mongo/blob/main/source/service.py#L16
`LOG_LEVEL` определен, но реально не используется. Это вводит в заблуждение, нарушение общепринятых правил в программировании.

https://github.com/ivangermes/testovoe_mongo/blob/main/source/service.py#L47
Это не информативный способ ответа - http клиент не получит никакой внятной информации о произошедшей ошибке, в логах тоже ничего не будет. Правильным будет либо явное указание ошибки (а в этом месте она точно известная) либо передача хотя бы служебной информации (если такое позволительно в проекте):
```python
try:
    time_from = isoparse(time_from_str)
except ValueError:
    raise HTTPBadRequest(f"Parameter 'time_from' has incorrect format: '{time_from_str}'")
```
```python
try:
    time_from = isoparse(time_from_str)
except ValueError as exc:
    raise HTTPBadRequest(exc)
```

https://github.com/ivangermes/testovoe_mongo/blob/main/source/service.py#L57
нету проверки на тот случай если заданы оба параметра и `time_from > time_to`. В таких случаях запрос вернет пустой результат, однако на деле это должно сигнализировать об ошибке входных данных.

https://github.com/ivangermes/testovoe_mongo/blob/main/source/service.py#L59
мне не ясно что такое SON. Если я предположу что это BSON, то данный TODO не имеет, на мой взгляд, практической ценности, поскольку итак будет происходить неявное преобразование этого словаря в BSON и без этого код будет компактнее и практичнее.

https://github.com/ivangermes/testovoe_mongo/blob/main/source/service.py#L93
Общепринятое использовать в таких случаях null/None, наличие любого другого статического значения предполагается быть осмысленным (необходимым для бизнес-логики). Таким образом повышается читаемость кода, так как фокус на этом не теряется.

https://github.com/ivangermes/testovoe_mongo/blob/main/source/service.py#L132
В отличии от других БД в монга работает со своими единицами хранилищ (коллекциями в данном случае) таким образом что нету необходимости в проверке или явном создании их. То есть если коллекции не будет. то данный проект все равно будет работать, а результат будет аналогичному если коллекция будет существовать пустой. Тоже самое и с добавлением документов - если коллекции в этот момент не будет, то она будет создана.
Поэтому данный кусок кода в практическом смысле скорее не нужен. Исключения могут быть, например если есть жесткой условие что коллекций должна быть, а ее отсутствие сигнал о проблеме и не нужно запускать сервис.

В целом хорошо.

**Comment by ivangermes** [comment]
> https://github.com/ivangermes/testovoe_mongo/blob/main/source/service.py#L93
> Общепринятое использовать в таких случаях null/None, наличие любого другого статического значения предполагается быть осмысленным (необходимым для бизнес-логики). Таким образом повышается читаемость кода, так как фокус на этом не теряется.

Это официальный способ удалить поле в представлении ( https://www.mongodb.com/docs/manual/reference/operator/aggregation/project/ ). 

> https://github.com/ivangermes/testovoe_mongo/blob/main/source/service.py#L132
> В отличии от других БД в монга работает со своими единицами хранилищ (коллекциями в данном случае) таким образом что нету необходимости в проверке или явном создании их. То есть если коллекции не будет. то данный проект все равно будет работать, а результат будет аналогичному если коллекция будет существовать пустой. Тоже самое и с добавлением документов - если коллекции в этот момент не будет, то она будет создана.
> Поэтому данный кусок кода в практическом смысле скорее не нужен. Исключения могут быть, например если есть жесткой условие что коллекций должна быть, а ее отсутствие сигнал о проблеме и не нужно запускать сервис.

Сервис интегрируется в уже существующую инфраструктуру и только собирается статистику ( только чтение).
Поэтому предполагается, что коллекция с данными уже есть.
Если при развертывании девпосы накосячат в окружении, монга создаст пустую коллекцию и будет отдавать пустые данные и этого никто не заметит.
IMHO в таком кейсе лучше получить явную ошибку.

Остальное пункты - fixed.
